"""Migration guide generator — templated markdown guides for package manager migration."""
from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from python_depot.ecosystem.models import PackageScan

# Supported migration directions with their guide templates
SUPPORTED_MIGRATIONS: dict[tuple[str, str], dict[str, Any]] = {
    ("pip", "uv"): {
        "title": "pip → uv Migration Guide",
        "config_changes": [
            {"file": "pyproject.toml", "change": "Add [tool.uv] section for uv configuration"},
            {"file": "pyproject.toml", "change": "Update build-system if needed (uv supports setuptools, hatchling, flit)"},
            {"file": "requirements.txt", "change": "Replace with uv.lock (auto-generated by uv sync)"},
        ],
        "steps": [
            "Install uv: curl -LsSf https://astral.sh/uv/install.sh | sh",
            "Run 'uv init' or 'uv add' to create uv.lock",
            "Convert requirements.txt with 'uv pip compile pyproject.toml -o uv.lock'",
            "Replace pip commands: 'uv add', 'uv remove', 'uv sync'",
            "Use 'uv run' instead of 'python -m' for script execution",
        ],
        "notes": "uv is 10-100x faster than pip and provides workspace support, Python version management, and a unified toolchain.",
    },
    ("poetry", "uv"): {
        "title": "Poetry → uv Migration Guide",
        "config_changes": [
            {"file": "pyproject.toml", "change": "Remove [tool.poetry] section"},
            {"file": "pyproject.toml", "change": "Replace [build-system] requires/build-backend with setuptools or hatchling"},
            {"file": "pyproject.toml", "change": "Move dependencies from [tool.poetry.dependencies] to [project.dependencies]"},
            {"file": "poetry.lock", "change": "Delete poetry.lock (uv will generate uv.lock)"},
        ],
        "steps": [
            "Install uv: curl -LsSf https://astral.sh/uv/install.sh | sh",
            "Run 'uv init' in the project directory",
            "Migrate dependencies from [tool.poetry.dependencies] to PEP 621 [project.dependencies] format",
            "Run 'uv lock' to generate uv.lock",
            "Run 'uv sync' to install dependencies",
            "Remove poetry.lock and pyproject.toml [tool.poetry] sections",
        ],
        "notes": "uv provides Poetry-like dependency resolution at 10-100x speed, with workspace support and Python version management.",
    },
    ("pip", "poetry"): {
        "title": "pip → Poetry Migration Guide",
        "config_changes": [
            {"file": "pyproject.toml", "change": "Add [build-system] requires = ['poetry-core'] and build-backend = 'poetry.core.masonry.api'"},
            {"file": "pyproject.toml", "change": "Add [tool.poetry] section with package metadata"},
            {"file": "pyproject.toml", "change": "Move dependencies from requirement files to [tool.poetry.dependencies]"},
            {"file": "requirements.txt", "change": "Replace with poetry.lock (auto-generated)"},
        ],
        "steps": [
            "Install Poetry: curl -sSL https://install.python-poetry.org | python3 -",
            "Run 'poetry init' to create pyproject.toml",
            "Run 'poetry add <dep>' for each dependency",
            "Run 'poetry lock' to generate poetry.lock",
            "Run 'poetry install' to install dependencies",
        ],
        "notes": "Poetry provides dependency locking, virtual environment management, and publishing workflow in a single tool.",
    },
    ("pip-tools", "uv"): {
        "title": "pip-tools to uv Migration Guide",
        "config_changes": [
            {"file": "requirements.in", "change": "Keep requirements.in for pinning top-level dependencies"},
            {"file": "requirements.txt", "change": "Replace compiled output with uv.lock (auto-generated by uv sync)"},
            {"file": "Makefile", "change": "Replace 'pip-compile' / 'pip-sync' targets with 'uv lock' / 'uv sync'"},
            {"file": "pyproject.toml", "change": "Add [tool.uv] section if uv configuration is needed"},
        ],
        "steps": [
            "Install uv: curl -LsSf https://astral.sh/uv/install.sh | sh",
            "Review requirements.in - uv can use it directly with 'uv pip compile'",
            "Run 'uv init' or manually add [project] metadata to pyproject.toml (uv supports PEP 621)",
            "Run 'uv lock' to generate uv.lock from your dependencies",
            "Run 'uv sync' to install everything into a virtual environment",
            "Replace pip-compile/pip-sync commands with uv equivalents in CI and local dev scripts",
        ],
        "notes": "pip-tools users get the fastest migration path to uv: the same requirements.in workflow but 10-100x faster resolution, a deterministic lockfile, and built-in virtual environment management.",
    },
}

_MIGRATIONS_WITH_PKG_COUNT: dict[tuple[str, str], dict[str, int]] = {
    ("pip", "uv"): {"estimated_packages": 12000},
    ("poetry", "uv"): {"estimated_packages": 5000},
    ("pip", "poetry"): {"estimated_packages": 3000},
    ("pip-tools", "uv"): {"estimated_packages": 2000},
}


class MigrationGuideGenerator:
    """Generate migration guides between Python package managers."""

    def __init__(self, db: Session | None) -> None:
        self._db = db

    def get_supported_migrations(self) -> list[dict[str, str | int]]:
        """Return the list of supported migration directions."""
        result = []
        for (from_m, to_m), details in _MIGRATIONS_WITH_PKG_COUNT.items():
            if (from_m, to_m) in SUPPORTED_MIGRATIONS:
                result.append({
                    "from": from_m,
                    "to": to_m,
                    "estimated_packages": details.get("estimated_packages", 0),
                })
        return result

    def generate_guide(
        self,
        package: str,
        from_manager: str,
        to_manager: str,
    ) -> dict[str, Any]:
        """Generate a migration guide for a specific package."""
        key = (from_manager, to_manager)
        template = SUPPORTED_MIGRATIONS.get(key)
        if template is None:
            raise ValueError(
                f"Unsupported migration: {from_manager} → {to_manager}. "
                f"Supported pairs: {list(SUPPORTED_MIGRATIONS.keys())}"
            )

        # Check if we have scan data for this package
        scan_data = None
        if self._db is not None:
            scan_data = (
                self._db.query(PackageScan)
                .filter(PackageScan.package_name == package)
                .first()
            )

        config_changes = template["config_changes"]
        steps = template["steps"]
        notes = template["notes"]

        # Add scan context if available
        contextual_notes = notes
        if scan_data:
            try:
                import json
                managers = json.loads(scan_data.managers_supported) if scan_data.managers_supported else []
                if to_manager in managers:
                    contextual_notes += (
                        f"\n\n**Compatibility Note**: {package} already supports {to_manager} "
                        f"according to our scan data. The migration should be straightforward."
                    )
            except (json.JSONDecodeError, TypeError):
                pass

        steps_text = "\n".join(f"{i+1}. {step}" for i, step in enumerate(steps))

        guide_md = (
            f"# {template['title']}\n\n"
            f"> **Package**: {package}\n"
            f"> **Migration**: {from_manager} → {to_manager}\n\n"
            f"## Configuration Changes\n\n"
        )
        for change in config_changes:
            guide_md += f"- **{change['file']}**: {change['change']}\n"

        guide_md += f"\n## Migration Steps\n\n{steps_text}\n\n## Notes\n\n{contextual_notes}\n"

        return {
            "package": package,
            "from_manager": from_manager,
            "to_manager": to_manager,
            "guide_markdown": guide_md,
            "config_changes": config_changes,
        }
